global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'producer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8081']

  - job_name: 'consumer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8082']

